version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/moduform
    overwrite: yes
permissions:
  - object: /home/ubuntu/moduform/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu