name: CD with Gradle

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

env:
  PROJECT_NAME: BE
  BUCKET_NAME: cicd-sobun-bucket
  CODE_DEPLOY_APP_NAME: cicd
  DEPLOYMENT_GROUP_NAME: cicd-module

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
        env:
          GITHUB_SHA: ${{ github.sha }}  # GitHub Actions에서 제공하는 커밋 식별자

      - name: Make Zip File
        run: zip -qq -r "$GITHUB_SHA.zip" .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp "$GITHUB_SHA.zip" "s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip"

      - name: Code Deploy To EC2 instance
        run: |
          aws deploy create-deployment \
            --application-name $CODE_DEPLOY_APP_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name $DEPLOYMENT_GROUP_NAME \
            --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
