name: Java CI with Gradle
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      #application.properties 만들기
      - uses: actions/checkout@v2
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
      - uses: actions/upload-artifact@v2
        with:
          name: application.properties
          path: ./src/main/resources/application.properties

      - name: Access aes.secret.key
        run: |
          echo "aes.secret.key : ${{ secrets.AES_SECRET_KEY }}"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle # test application build
        run: ./gradlew --info test
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build